### ISSUE TITLE
SWA - consistent response payload

### ISSUE THREAD

**Issue by michaelbinks** [Azure/static-web-apps#1281]
**Describe the bug**

We host a vue.js applcation on SWA. We had a recent issue where a 3rd party script rendered the application useless. JS error and resulting whitescreen. Once we found the issue we deployed a new version (removing the offending script tag) of the app to SWA. This was ~21:30 15/09/2023 BST. However post 23:00 on the same date we were still seeing some requests to index.html on the SWA returning the script tag as part of the response payload. Sadly this meant that whist we had fixed the issue the SWA was still serving a version that was breaking the site for the customer.

Are we able to get any clarification on the reasonings for this type of behaviour.

- staticwebapp.config.json file
{
  "globalHeaders": {
    "Cache-Control": "no-store"
  },
  "routes": [
    {
      "route": "/apple-app-site-association",
      "rewrite": "/apple-app-site-association.json"
    }
  ],
  "navigationFallback": {
    "rewrite": "/index.html",
    "exclude": ["/images/*.{png,jpg,gif}", "/css/*"]
  }
}

**Expected behavior**
Following a deployment of a static resource the expected payload will be returned consistently. I understand this is a global service so looking for an understanding of how long it could take to achieve this. MS docs are not helping

**Screenshots**

**Device info (if applicable):**
all/any

**Additional context**

**Comment by akselikap** [comment]
We faced a similar issue which we received a report for at 12.00 UTC time today. I have created a support ticket to Azure about this. Our issue is as follows:
SWA returns index.html. Index.html starts with our React JavaScript bundle script tags. We have 2 bundle files. So from the network tab it looks like:
1. index.html
2. bundle1-hash.js
3. bundle2-hash.js

Starting today at 12.00 UTC time the bundle2-hash.js will randomly return 404 error. E.g. if I spam the reload button of a browser on our site 10 times within 10 seconds it could return 5 404 errors and 5 200 successes. All 404 errors lead to our React application crashing and displaying a blank white screen.

In addition to this it's also clear that the SWA could randomly return a different index.html file which most likely belonged to a previous deployment of the SWA. This can also be observed from the network tab because the hashes of the included script tags change randomly when you spam the reload button of the browser.

We have 4 SWAs which are built from the same code and deployed using the same pipeline. 3 of them are experiencing the issue. The only difference I could think of between the applications is that the other 3 are created earlier compared to the one that is still working.

**Comment by akselikap** [comment]
I got confirmation from Azure that the fault is indeed on their end. Haven't gotten a confirmation that it has been fixed but it seems like it's fixed now.

**Comment by jgarplind** [comment]
> Haven't gotten a confirmation that it has been fixed but it seems like it's fixed now.

Personally I am still seeing the issue intermittently, so I don't think there has been a fully rolled out fix yet.

**Comment by serhatkepez** [comment]
> I got confirmation from Azure that the fault is indeed on their end. Haven't gotten a confirmation that it has been fixed but it seems like it's fixed now.

Unfortunately still having this issue

**Comment by lud-hu** [comment]
We are also experiencing these issues since yesterday and it's making our site not usable at all. I hope they will come up with a fix for this quickly...

**Comment by mm-edtake** [comment]
Same problem here.
Trying to change engine, bundle size, staticwebappconfg, nothing is working.

**Comment by MarkTallentire** [comment]
We've been facing issues with atomic deployments for the last 3 days.

Refreshing our site serves different versions randomly and sometimes produces 404s
![image](https://github.com/Azure/static-web-apps/assets/26217534/cbd92b68-c3e7-4d19-a4d7-9701b5465dfb)

This is causing issues with our production environments.

**Comment by bengreenow** [comment]
Same issue here, seems almost round robin-y

Reload: Works!
Reload: Works!
Reload: 404 hell...
Reload: Works!

**Comment by akselikap** [comment]
Just got a response from Azure:

> The investigation is still ongoing.
> 
> The Product group team provided the following mitigation steps:
> 
>  
> 
> Perform a redeployment without any user interruption (like cancel, redeploy, multi deploy ...).
>  
> 
> After the redeploy, the issue should be mitigated. Once you’re able to redeploy, let us know, and we’ll monitor to check if any 404 will still be appearing.

I haven't tested these instructions myself because our system appears to be working already.

**Comment by MarkTallentire** [comment]
> Just got a response from Azure:
> 
> > The investigation is still ongoing.
> > The Product group team provided the following mitigation steps:
> > Perform a redeployment without any user interruption (like cancel, redeploy, multi deploy ...).
> > After the redeploy, the issue should be mitigated. Once you’re able to redeploy, let us know, and we’ll monitor to check if any 404 will still be appearing.
> 
> I haven't tested these instructions myself because our system appears to be working already.

This didn't resolve anything for us. Deployed via Azure Devops Pipelines. Still random 404s on refresh.

**Comment by akselikap** [comment]
Is there any way to actually see if the error is still occurring? Does something like access log exist for Static Web Apps? I couldn't come up with one myself.

**Comment by MarkTallentire** [comment]
> Is there any way to actually see if the error is still occurring? Does something like access log exist for Static Web Apps? I couldn't come up with one myself.

No, seems to all be hidden away. We can replicate pretty easily by just hitting F5 a few times now.

**Comment by akselikap** [comment]
> No, seems to all be hidden away. We can replicate pretty easily by just hitting F5 a few times now.
I'm unable to replicate it that way so maybe it's fixed or then it doesn't occur as frequently anymore. Kind of annoying that there's no way for me to monitor my own application. At least you should be able to just connect it to Application Insights and have the request logs there or some metric about HTTP codes etc.

**Comment by nicktolhurst** [comment]
> Kind of annoying that there's no way for me to monitor my own application.

Agreed. There is this workaround to provide some deeper analytics, you would have to create a standalone application insights resource and then hook it up with this snippet: https://github.com/Microsoft/ApplicationInsights-JS#snippet-setup-ignore-if-using-npm-setup

I am still seeing this issue fairly often. Around 1 in every 10 requests returns 404.

**Comment by MarkTallentire** [comment]
> I am still seeing this issue fairly often. Around 1 in every 10 requests returns 404.

Following a re-deployment to our test system the issue became much more apparent again. I'm assuming its some kind of propogation issue to various edge endpoints and the 404 occurs when you hit one that hasn't started running the new container yet.

**Comment by nikoraes** [comment]
> > I am still seeing this issue fairly often. Around 1 in every 10 requests returns 404.
> 
> Following a re-deployment to our test system the issue became much more apparent again. I'm assuming its some kind of propagation issue to various edge endpoints and the 404 occurs when you hit one that hasn't started running the new container yet.

I agree. 
We are having the same issue since last week. After deployment we get 404s on random files but after about 6 hours everything seems to work again. So redeploying definitely doesn't solve anything as it then takes seems to take longer for everything to work again.

**Comment by MarkTallentire** [comment]
Just to confirm we've raised with our CSP who have raised with MS. Will update if anything new comes back

**Comment by Duske** [comment]
Experienced the same issue since 15-09-2023 together with other users: https://learn.microsoft.com/en-us/answers/questions/1369563/404-errors-in-azure-static-web-app-js?comment=question#newest-question-comment

Happens in both tiers, Free and with SLA

**Comment by AjayKumar-MSFT** [comment]
Duske, Thanks for adding the [Q&A thread.](https://learn.microsoft.com/en-us/answers/questions/1369563/404-errors-in-azure-static-web-app-js?comment=question#newest-question-comment) 

I understand that this is causing inconvenience. I am currently collaborating internally with our product engineering team, and I will provide an update as soon as more info becomes available.  We appreciate your patience!

**Comment by thomasgauvin** [comment]
We're mitigating and investigating the cause, will provide updates when we can!

**Comment by annikel** [comment]
If you've been affected by this issue, we kindly request that you provide us with additional details about your static web apps, such as the default hostname. Sharing this information will assist and expedite our investigation. If you prefer not to share this information here, please open a support ticket.

**Comment by jgarplind** [comment]
> If you've been affected by this issue, we kindly request that you provide us with additional details about your static web apps, such as the default hostname. Sharing this information will assist and expedite our investigation. If you prefer not to share this information here, please open a support ticket.

There is a support ticket with the tracking ID 2309190050003017 for your reference

**Comment by Duske** [comment]
> If you've been affected by this issue, we kindly request that you provide us with additional details about your static web apps, such as the default hostname. Sharing this information will assist and expedite our investigation. If you prefer not to share this information here, please open a support ticket.

Support ticket for your reference: 2309200050000814
Details about webapp:
- built with vue.js and bundled with Vite
- SLA tier and free tier affected
- the longer deployment is active, the less 404 you seem to get (CDN propagation issue?)
- no API, functions, database involved. A very plain SWA
- deployed via github action  Azure/static-web-apps-deploy@v1

**Comment by bengreenow** [comment]
> > If you've been affected by this issue, we kindly request that you provide us with additional details about your static web apps, such as the default hostname. Sharing this information will assist and expedite our investigation. If you prefer not to share this information here, please open a support ticket.
> 
> Support ticket for your reference: 2309200050000814 Details about webapp:
> 
> * built with vue.js and bundled with Vite
> * SLA tier and free tier affected
> * the longer deployment is active, the less 404 you seem to get (CDN propagation issue?)
> * no API, functions, database involved. A very plain SWA
> * deployed via github action  Azure/static-web-apps-deploy@v1

Our situation is identical, however we deploy from Azure Pipelines via DevOps

**Comment by vegaasen** [comment]
Lots of problems here too. Web-app structure:

* Simple/Plain React/Typescript-application packaged using Vite - plain SWA
* No APIs
* No functions
* Built through Azure DevOps
* Deployed through Azure DevOps using the following configuration:
  * ```yaml
          - task: AzureStaticWebApp@0
            displayName: Upload to Azure Static Webapp
            inputs:
              app_location: '$(Build.ArtifactsDirectory)/build'
              output_location: ''
              skip_app_build: true
              azure_static_web_apps_api_token: $(<masked>)
   ``` 
* 404 expierienced when refreshing the SWA domain. Looks to be refrerring to old versions of the, as the cache-busting identifiers we have in place is referencing to old elements. As mentioned above here, it looks to sort of be related to CDN or something similar?
  * Seen two-three old releases
  * Deployed eight times, and seen atleast seven of those eight whist refreshing the site 😅 
* We're not quite sure, but 15th of september seems to be the date for when the problems started for us too

**Comment by MarkTallentire** [comment]
> Lots of problems here too. Web-app structure:
> 
>     * Simple/Plain React/Typescript-application packaged using Vite - plain SWA
> 
>     * No APIs
> 
>     * No functions
> 
>     * Built through Azure DevOps
> 
>     * Deployed through Azure DevOps using the following configuration:
>       
>       * ```yaml
>               - task: AzureStaticWebApp@0
>                 displayName: Upload to Azure Static Webapp
>                 inputs:
>                   app_location: '$(Build.ArtifactsDirectory)/build'
>                   output_location: ''
>                   skip_app_build: true
>                   azure_static_web_apps_api_token: $(<masked>)
>         ```
> 
>     * **SLA**-tier and **Free**-tier affected
> 
>     * `404`s experienced when refreshing the SWA domain. Looks to be refrerring to old versions of the, as the cache-busting identifiers we have in place is referencing to old elements. As mentioned above here, it looks to sort of be related to CDN or something similar? We've noticed:
>       
>       * Seen two-three old releases
>       * Deployed eight times, and seen atleast seven of those eight whist refreshing the site 😅
> 
>     * We're not quite sure, but 15th of september seems to be the date for when the problems started for us too

This is identical to our setup. 
We have a ticket raised through our CSP already (unfortunately they haven't provided us a reference number)

**Comment by akselikap** [comment]
I received a confirmation from Azure that this issue should be mitigated now. I also got a very brief description about the root cause.

> the 404 logs originate from the Frontend ([Azure - Inside the Azure App Service Architecture | Microsoft Learn](https://learn.microsoft.com/en-us/archive/msdn-magazine/2017/february/azure-inside-the-azure-app-service-architecture#front-end)) — a layer seven load balancer in the App Service Architecture.

**Comment by MarkTallentire** [comment]
> I received a confirmation from Azure that this issue should be mitigated now. I also got a very brief description about the root cause.
> 
> > the 404 logs originate from the Frontend ([Azure - Inside the Azure App Service Architecture | Microsoft Learn](https://learn.microsoft.com/en-us/archive/msdn-magazine/2017/february/azure-inside-the-azure-app-service-architecture#front-end)) — a layer seven load balancer in the App Service Architecture.

Thanks for the update. Everything appears to be working and stable on our side as well. 
Disappointed in the response by Microsoft (Zero updates on official channels, issue hasn't even been noted on Service Health etc..) but that's a different story.

**Comment by jgarplind** [comment]
Also unable to reproduce the error straight away, but being intermittent in nature, it is hard to say if something is fully resolved.

**Comment by dagskage** [comment]
@thomasgauvin / @AjayKumar-MSFT - can you confirm that the issue is fully resolved?

**Comment by annikel** [comment]
I am confirming that the issue has been successfully resolved as of yesterday. Thank you for bringing this matter to our attention, and we appreciate your patience throughout the resolution process.

**Comment by thomasgauvin** [comment]
As confirmed by @annikel, this issue is now resolved

**Comment by mm-edtake** [comment]
Hi @thomasgauvin 

It seems not completely resolved. 

- [x] If i navigate from root to page => OK
- [x] If i refresh (F5) => OK
- [ ] If refresh no cache (Shift+F5) => 404 (Azure 404 even if we have our own 404 page)
- [ ] Access using private navigation => 404 (Azure 404 even if we have our own 404 page)
