### ISSUE TITLE
Nextjs backend call failure

### ISSUE THREAD

**Issue by krisnashaypp** [Azure/static-web-apps#1444]
We have a nextjs app that has been running as a static web app for many months, in recent days it has started having intermittent failures were all you see is "Backend call failure", usually it starts working by itself after a while but sometimes it takes a longer time.

![image](https://github.com/Azure/static-web-apps/assets/144227209/406ad2a7-84d2-4b07-974a-35b774d8a9d0)

It's running next 13.5.6, thanks

**Comment by mmcossu** [comment]
Same thing here, randomly, out of nowhere, with next.js 14.1.0 with app routing .
As of today it only happened once, this monday, and we could not identify any cause.

**Comment by lucas-garrido** [comment]
Same here... its rly annoying

**Comment by DervishMarauder** [comment]
I've had to migrate away from using Static Web App resources because these past few days have been non-stop outages with this exact error. I hope that they resolve this soon as it seemed like a simpler alternative than hosting everything in a kubernetes cluster, but having this pop up for production applications that previously worked without issue isn't something that anybody wants to handle. 

Good luck to everyone and I hope that a response / solution is raised for this soon.

**Comment by thomasbtf** [comment]
Same here unfortunately. Using the free tier.

**Comment by davidhancockilfracombe** [comment]
Don't worry, M$ are on it! :S

**Comment by jpaholik** [comment]
The same problem here

**Comment by AndreasAKD** [comment]
We get this more frequently on both of our webapps for the last month and it's getting worse, what's going on??

**Comment by serena-shen2** [comment]
Hi there, would you all be able to share your site's defaultHostname or raise an issue against our service so we can continue to investigate?

**Comment by krisnashaypp** [comment]
> Hi there, would you all be able to share your site's defaultHostname or raise an issue against our service so we can continue to investigate?

Hi Serena, our defaultHostname = lively-grass-00c911a03.3.azurestaticapps.net

**Comment by mmcossu** [comment]
@serena-shen2 https://zealous-rock-01a3ede03.4.azurestaticapps.net

**Comment by psegalen** [comment]
Hi, my paid tier SWA has these intermittent errors since march 22nd, I also observed something that wasn't there before: when a page goes 404 on purpose, next never tries to get it again, it just stays a 404 until a new deployment occurs.
I really think it's related to the nextjs improvements published by the team on march 7th, here are more about my specific case: https://github.com/Azure/static-web-apps/discussions/1066#discussioncomment-9079775
I'd be happy to raise an issue and work with your service to mitigate this @serena-shen2, how can one do it?

**Comment by krisnashaypp** [comment]
Hi, I finally moved the app to azure container apps instead because we were having this problem daily. I'll leave the issue open of course but we have stopped using static web app so you can ignore looking into our defaultHostname @serena-shen2

**Comment by angusb93** [comment]
This is becoming a big problem for me too. Noticing the same sluggishness before the site goes down

**Comment by liamfiddler** [comment]
I'm seeing the same issue on a site I support for a client.

The site has been crashing almost daily for the past week with "Backend call failure" messages.

Like @psegalen [mentioned in their comment](https://github.com/Azure/static-web-apps/discussions/1066#discussioncomment-9079775), I've found that performing a manual re-run of the latest Github Action can temporarily resolve it.

**Comment by ottosulin** [comment]
We're getting these at least once a day. Azure support is completely clueless about this.

**Comment by selimeneserdogan** [comment]
We are experiencing the same issue. The test environment for the same project is hosted on free AWS Amplify, and we are not encountering any similar errors or slowdowns. For now, it seems there is no solution…

**Comment by nmoliveira** [comment]
Same issue!

**Comment by vonbv** [comment]
We have encountered this too just today. Our static web app has not been touched since 5 days ago and it has been running fine. Re-running the last deployment we did fix the problem for us. Not a real solution though as we need more data into what happened. Our app's app insights is not showing anything for us.

**Comment by jenspettersson** [comment]
Same issue here since _at least_ a week ago  (might have been earlier). We had to deploy a second instance of our SWA because we can't even deploy to our original:

```
The content server has rejected the request with: BadRequest
Reason: The Static Web App contents cannot be updated while a backend migration is in progress.
```

The new instance also gets the `Backend call failure` randomly and is sluggish as well, but at least it kind of works... sometimes.

**Comment by vartdalen** [comment]
We started seeing this error for the first time today. It seems to happen on deployment to both preview and production. Redeploying has fixed the issue one time so far. Very unreliable and unpredictable, hope Microsoft will address this?

**Comment by vonbv** [comment]
We encountered this again today and running the last deployment did not fix it this time. We tried doing it three times and with each successful deployment, the website just shows the "Backend call failure" message. So we decided to create a new SWA and the site is backed up. That process it no sustainable.

**Comment by Jbveas01** [comment]
We have been experiencing the same issue around ~3:40 EST a few times a week without us touching anything.  Usually comes back up in 10-15 minutes. The only backend part of our SWA is our NextAuth authorization

**Comment by psegalen** [comment]
Hi all, I don't know this has anything to do with an action from the Azure team but our production NextJS app hasn't crashed for a whole week, this is a nice change!
Kudos to MSFT teams if it's their doing!

**Comment by enesceb** [comment]
Until now, the environment was supposed to crash at least once, but I just realized that it didn't. Do you think the problem may have been solved?

**Comment by psegalen** [comment]
> Until now, the environment was supposed to crash at least once, but I just realized that it didn't. Do you think the problem may have been solved?

I really hope so! 🤞

**Comment by Ambyli** [comment]
> Hi all, I don't know this has anything to do with an action from the Azure team but our production NextJS app hasn't crashed for a whole week, this is a nice change! Kudos to MSFT teams if it's their doing!

Unfortunately for us, it has crashed and been down for at least a minute every day last week. Oddly always at the same time in the afternoon in EST?

**Comment by sellimenes** [comment]
It seems like the problem has been resolved for the past few days. However, since we don't have concrete data, I cannot say anything definitive. I only synchronized the fetch operations on the SSR pages with Promise.all in terms of performance. I'm not sure if this could have an effect, but I suggest to try.

**Comment by liamgsmith** [comment]
Can confirm it's still happening as of just now; two sites on free ; https://ambitious-desert-0308b531e.5.azurestaticapps.net/ and https://mango-flower-0ef1f931e.5.azurestaticapps.net/.
Both worked again after a few minutes of getting the backend call failure
Guessing it's some kind of warm up / time out combinatoin where there host is turned off and needs to respond after a period of inactivity; felt a bit like the old Heroku plans used to.

**Comment by psegalen** [comment]
> ... Guessing it's some kind of warm up / time out combinatoin where there host is turned off and needs to respond after a period of inactivity; felt a bit like the old Heroku plans used to.

I don't think so, having way too issues a month ago I created a probe on my Azure Functions that tests a SSR page of our NextJS app (it's a CRON running every 5 minutes, that's how I could monitor the frequency of crash happening) so I think our NextJS app (and SWA) never goes cold but it would crash anyway.

**Comment by mattfrear** [comment]
> Have contacted Azure and they've reported they're working on it. They've shared that fixes have been rolled out to East Asia and West US 2 regions. Anyone in either of these two regions still having issues?

I have an Azure SWA in East Asia and I'm seeing that error for the first time today. Although, in the Azure Portal now the location says "Global".

**Comment by ottosulin** [comment]
SWAs are replicated eventually globally, but from the Azure API's perspective you first deploy it to one region, where I guess the original versions of the assets are stored.

And we're still experiencing this issue too daily.

**Comment by CatalinBalan** [comment]
Any news? This is a critical issue and seems many people are experiencing it.

**Comment by iaggocapitaniovamo** [comment]
same issue here

**Comment by mattfrear** [comment]
FWIW I'm not seeing this any more (East Asia). I was seeing it when I was having some auth issues, occasionally I'd get 401s and occasionally I'd see "Backend call failure" (can't remember with which response code).

**Comment by MichaelZh1104** [comment]
same issue here

**Comment by victorpotasso** [comment]
Same issue here

**Comment by jenspettersson** [comment]
Was working ok for us the last week, but now we're facing:

<img width="222" alt="image" src="https://github.com/Azure/static-web-apps/assets/125493/2bec0bc1-2758-42fd-87ea-b78ba7f1615b">

Backend call failure again... And still no _official_ statement as far as I can see... SWA does NOT feel like something you want to invest in for the future...

**Comment by janosgy** [comment]
We've been experiencing this issue more and more often since the last week. Last time it was not recovering on its own even after several hours. 
What helped is that we re-deployed the application and the issue was gone.
I hope this helps.

**Comment by jenspettersson** [comment]
> We've been experiencing this issue more and more often since the last week. Last time it was not recovering on its own even after several hours. What helped is that we re-deployed the application and the issue was gone. I hope this helps.

Thanks, a re-deploy "fixed" it. For now.

**Comment by D1slife** [comment]
Is this happening for apps that use SSR or CSR?

**Comment by amfjardel** [comment]
Same problem :(

**Comment by JardelFelp** [comment]
Same problem :(

**Comment by Vbaungartem** [comment]
Same problem here :(

**Comment by gfrnca** [comment]
Same problem here, too.

**Comment by victorpotasso** [comment]
Same issue and I'm running a Next.js 14 on a SWA in US. I'm making use of SSR

**Comment by yhpredeyes** [comment]
Same issue here as well with Next version "13.2.4"

**Comment by EmanH5** [comment]
After struggling from the same problem, this is how I fixed it for my app. First, no work around worked for me on Azure static web app even the paid plan! So I shifted to Azure app service and it won't work until you include some files and modifications. I wrote all about it and added the files needed, code and references [here](https://medium.com/@emhassan/how-to-avoid-backend-failures-when-hosting-a-next-js-application-on-azure-f64125b1c04b)
Just jump to the solution part.

I hope this helps.

**Comment by janosgy** [comment]
> After struggling from the same problem, this is how I fixed it for my app. First, no work around worked for me on Azure static web app even the paid plan! So I shifted to Azure app service and it won't work until you include some files and modifications. I wrote all about it and added the files needed, code and references [here](https://tech-api.com/2024/05/26/how-to-avoid-backend-failures-when-hosting-a-next-js-application-on-azure/) Just jump to the solution part.
> 
> I hope this helps.

@EmanH5 
I also migrated to App Service, but there was no need to do manual configuration or change the scripts in the package.json.
This is the guide I followed: https://dev.to/paulriviera/deploy-nextjs-14-app-to-linux-azure-app-service-3d34
and I think most of the things are done automatically because of the `standalone` output config.

**Comment by EmanH5** [comment]
> > After struggling from the same problem, this is how I fixed it for my app. First, no work around worked for me on Azure static web app even the paid plan! So I shifted to Azure app service and it won't work until you include some files and modifications. I wrote all about it and added the files needed, code and references [here](https://tech-api.com/2024/05/26/how-to-avoid-backend-failures-when-hosting-a-next-js-application-on-azure/) Just jump to the solution part.
> > I hope this helps.
> 
> @EmanH5 I also migrated to App Service, but there was no need to do manual configuration or change the scripts in the package.json. This is the guide I followed: https://dev.to/paulriviera/deploy-nextjs-14-app-to-linux-azure-app-service-3d34 and I think most of the things are done automatically because of the `standalone` output config.

@janosgy That's weird, I tried it without changing package.json but it didn't work at all. in my experience the only approach that worked with me was adding the server abd config files and change package.jsob scripts to node
Maybe it depends on next version then? not sure really but at least it is for sure needs to be an Azure app service to work 👍🏻

**Comment by sellimenes** [comment]
It is unacceptable and shameful for Azure to leave such a serious problem unexplained. We have switched from Azure SWA to IIS. Everything works much much faster, the build configuration is much easier, and we are not encountering any unexplained errors. For those experiencing the problem, the only absolute solution seems to be not using SWA...

NOTE: We were using paid plans.

**Comment by mfathi91** [comment]
@janosgy
@EmanH5 
we also have a Next.js static web app (where both frontend and backend are hosted on the static web app itself). Did you guys move your backend only to Azure App Service? Or your entire application?

This is how I do it on Azure, but I get "Internal Server Error":
1. Create an app service plan with P1V3 tier, with Linux OS.
2. Create a web app an associate it with the app service plan.
3. In Azure portal, go to the static web app -> APIs -> Configure linked backend -> add the created linux web app

**Comment by tirabassi** [comment]
Here we are with the same problem, on the standard plan

**Comment by victorpotasso** [comment]
We also moved to app service. So far so good. We also noticed the application is performing better. It also catch more next.js exceptions to App Insights

**Comment by charlower** [comment]
Experiencing the same issue for a while now.

**Comment by EmanH5** [comment]
> @janosgy @EmanH5 we also have a Next.js static web app (where both frontend and backend are hosted on the static web app itself). Did you guys move your backend only to Azure App Service? Or your entire application?
> 
> This is how I do it on Azure, but I get "Internal Server Error":
> 
> 1. Create an app service plan with P1V3 tier, with Linux OS.
> 2. Create a web app an associate it with the app service plan.
> 3. In Azure portal, go to the static web app -> APIs -> Configure linked backend -> add the created linux web app

@mfathi91 I moved the entire app to Azure app service and it is working smoothly now with the configurations I mentioned in my post. 
Your steps also make sense as another approach that could work if you want to only move the backend but since you have internal server error then there might be an issue with the APIs setup or the Access permissions to the Azure App service. Maybe CORS? not sure.

**Comment by lucavgobbi** [comment]
We've been having the same issue, what has helped is trying to update a dummy "environment variable" to trigger a back-end restart. If that doesn't help, trigger the same deploy has helped.

**Comment by philipmuller** [comment]
Same issue here. Paid SWA service in West Europe. Only fix is redeploying

**Comment by mrcportillo** [comment]
Same issue here with paid SWA service. 🔥 🔥

**Comment by alexeisolodovnicov-tomtom** [comment]
Hybrid NextJS apps are still in Preview, so MSFT support wouldn't help much. The only way seems to jump to Azure App Service.

**Comment by ElHawary-Ebutler** [comment]
Same issue.

**Comment by vartdalen** [comment]
Same issue Next.js 14.2.3 with NextAuth 4.24.7, redeploying seems to fix the problem - after redeploying yesterday, the issue has not resurfaced yet.

**Comment by mrcportillo** [comment]
After several days with the same issue I moved to app services. Used this guide for the project setup https://dev.to/paulriviera/deploy-nextjs-14-app-to-linux-azure-app-service-3d34 and as I'm using azure pipelines I followed this https://www.azure365pro.com/deploy-next-js-app-on-azure-app-service-with-azure-devops-pipelines-2/ for the pipeline script and the service connection configuration. Something to point out, had some issues when using the free tier app service layer, after moved to the paid one it just worked 🤑

**Comment by krisnashaypp** [comment]
OP here, I moved my app to Azure Container Apps and i've been very pleased with that service so far. With little knowledge about docker and ACA I was able to get up and running within a day and now I'm moving my backend into the same service since you get a lot of synergies. I recommend everyone give it a look before automatically going with app service.

**Comment by JiRadu** [comment]
I moved from it to vercel.
Muck Ficrosoft

**Comment by TimKerre** [comment]
Same issue here, using NextJS 14 on Paid SWA service

**Comment by ChandanRabha** [comment]
Experiencing the same issue, build runs no issue locally, but when done on azure pipelines sometimes build is created successfully and sometimes it isn't. And the error message of the post. Using Next 14

**Comment by hrc7505** [comment]
We are facing same issue
Nextjs: 14.2.3
Node: 20.11.0

**Comment by tommykri** [comment]
We are also experiencing the same issue on a paid SWA service and is considering other options if this isn't fixed soon. Occasionally the API routes is very slow or we get the error message "Backend call failure".

**Comment by janosgy** [comment]
I believe this issue will only grow. It seems that Azure functions are not production-ready.
If you can, move away from Azure, if you can't, migrate to App Service.

**Comment by dharmendrasha** [comment]
same here

**Comment by TomiwaPhilip** [comment]
I am also experiencing the same issue

**Comment by dharmendrasha** [comment]
for those who are suffering this fixed my issue.

https://github.com/Azure/static-web-apps/issues/1496#issuecomment-2168383060

**Comment by jenspettersson** [comment]
> for those who are suffering this fixed my issue.
> 
> [#1496 (comment)](https://github.com/Azure/static-web-apps/issues/1496#issuecomment-2168383060)

I think most of us in this thread have issues with the application suddenly stops working with the "Backend call failure" message. The deploys have been flaky but I don't think that's the real underlying issue.

We had "Backend call failure" this morning and a re-deployed "fixed" it, but I can assure you we will soon see the "Backend call failure" again. Just happy we're not using it for anything else than a small internal app... Even so, we're currently migrating away from SWA and will use Container Apps instead as this is not acceptable at all.

**Comment by vartdalen** [comment]
After redeploying upon encountering this issue a few weeks ago, the issue was temporarily fixed until today. Had to redeploy again for temporary fix. Microsoft, please look at this issue.

**Comment by jenspettersson** [comment]
We've now moved away from SWA to Azure Container Apps and the migration was a breeze. It feels so much more stable now. It isn't free, but it's very cheap.

I used this example to start us off: https://github.com/vercel/next.js/tree/canary/examples/with-docker

**Comment by mike-rambil** [comment]
Same issue here as well..

**Comment by designitsecure** [comment]
Adding my voice to the chorus of those running into this issue. I was really hoping SWA would be a viable solution. Off I go to build a container I guess....

**Comment by mike-rambil** [comment]
same issue here

**Comment by LifeLike1** [comment]
same issue

**Comment by iwgarcia** [comment]
same issue here

**Comment by christie-hill-za** [comment]
I am having the same issue with a Nuxt 3 app. Today has been insane. So much downtime and the usage looks okay, not like we have more traffic than usual.

![image](https://github.com/Azure/static-web-apps/assets/83393649/47e84e11-723d-4cf3-90d8-7963ed60166c)

**Comment by Tottzi** [comment]
Same her. Everything workd just fine until today. Now, I'm getting this error very often. 
Static Web App
Next.js 14.2.4

**Comment by vartdalen** [comment]
This issue has not affected our solution for the past 3 weeks - no changes have been made to the source code.

**Comment by ottosulin** [comment]
We're still detecting this, although less often currently around once per day for 5-10 minutes.

**Comment by psegalen** [comment]
On our side, we had an awful day on the 17th (patch day?) but no more outage since then.
Hopefully the issue has been solved? 🤞

**Comment by JiRadu** [comment]
is this solved?

**Comment by vartdalen** [comment]
I got the backend call failure issue today, only in preview environment. Refreshed two times and it recovered

**Comment by lucas-garrido** [comment]
Currently trying to run next 14 hybrid application, performances are terrible, still having backend failures every time. this is nearly unusable, and we pay for it....

**Comment by andresmmujica** [comment]
We just face this issue today on production environment, previously we had it on development but didn't find anything at all and it stopped to happen so we disregard it, however today it blew in our faces again in both production and development... Not sure what to do to overcome this, logs doesn't show anything related, there's no new code pushed for weeks

**Comment by eimerreis** [comment]
Also facing this issue with next 14 (app router)

 ![Image](https://github.com/user-attachments/assets/5876ce25-7fa0-41f8-a15b-9f1d83be1762)

**Comment by Seb0927** [comment]
I'm currently getting this error as well! Specially from the moment I started using App Routing :/

**Comment by Seb0927** [comment]
I'm currently getting this error as well! Especially from the moment I started using App Routing :/

**Comment by SantoshPisini** [comment]
Facing the same issue.

**Comment by christhompson1** [comment]
same issue here, on a vite / vue build

**Comment by TomiwaPhilip** [comment]
Just use a container. Deploy with App Service

**Comment by jimlundblad** [comment]
just encountered the same issue when trying to use a linked backend

**Comment by nsuntiphp8824** [comment]
Hello, is there any update?

**Comment by matt-gribben** [comment]
Also having this issue, running NextJS 14.2.21, works correctly locally and the rest of the frontend works as expected but we have a callback url of /api/tenant-callback that is throwing this error... unfortunately this is fundamental functionality for our app. Any ideas?

**Comment by oudon-mizusawa** [comment]
Maybe I solve it. now My App doesn`t occur this problem.

According to [article](https://tech-api.com/how-to-avoid-backend-failures-when-hosting-a-next-js-application-on-azure-f64125b1c04b), Maybe Azure Static App actually use IIS. To do so, Unconsidering to Dynamic Routing like Next.js. this articles teach us how resolve this issues.

We need to set IIS config file(web.config) on Your App. and all request direct to Nodejs from IIS, so you can solve it.

**Comment by oudon-mizusawa** [comment]
I had the opportunity to discuss this issue with a Microsoft partner company, so I would like to share it with you.

Azure Static App is literally used for static sites (html, css, etc.), and it was recommended to use AppService.

With AppService, you can build code using github action, Azure Pipeline, etc. and reflect it on the site as is, but the code build time is unusually long, and the build machine uses Microsoft's Linux called kudu linux, so the operation is questionable, such as failing to install various libraries.

Personally, I think the best way to run apps such as Nextjs is to build them using Docker, upload them to Azure Container Registry, and then use that to run App Service.

Integrating App Service and Container Registry is very easy and takes very little time to build and deploy.

Also, if the scale of development increases, it is also a good idea to use a k8s-based service called Container App from App Service. This also deploys a Docker image, making it highly portable.

**Comment by jameseedi** [comment]
We also had this issue reported by a client using our web app. I hadn't experienced the issue and I think this might have only occurred once! Through caution, and without seeing a "fix" for this, we migrated to App Service. However, it's worth noting that when you create a new static web app in Azure you literally get a "Build Preset" option for NextJs! If this isn't fully supported I suggest you either remove or you add a warning about server side components / versions that may cause this issue. To save anyone else having these problems.

<img width="760" height="859" alt="Image" src="https://github.com/user-attachments/assets/6e9c5163-e7ea-4c50-acb0-cb0ee212eacf" />

**Comment by Tottzi** [comment]
> I had the opportunity to discuss this issue with a Microsoft partner company, so I would like to share it with you.
> 
> Azure Static App is literally used for static sites (html, css, etc.), and it was recommended to use AppService.
> 
> With AppService, you can build code using github action, Azure Pipeline, etc. and reflect it on the site as is, but the code build time is unusually long, and the build machine uses Microsoft's Linux called kudu linux, so the operation is questionable, such as failing to install various libraries.
> 
> Personally, I think the best way to run apps such as Nextjs is to build them using Docker, upload them to Azure Container Registry, and then use that to run App Service.
> 
> Integrating App Service and Container Registry is very easy and takes very little time to build and deploy.
> 
> Also, if the scale of development increases, it is also a good idea to use a k8s-based service called Container App from App Service. This also deploys a Docker image, making it highly portable.

We moved to a Docker so this issue is gone.

**Comment by hernan-almeida** [comment]
I have been using the paid version for about over a year and never had an issue with this. All of the sudden the app started crashing at around midnight and early mornings (MST). Redeploying always solved the issue so I wrote a quick logic app to ping the site and re-deploy via GitHub actions if the app was unresponsive. Not a permanent solution, but it minimized downtime to about 3 minutes.

Observability with static sites is terrible, even with insights enabled, you can't see any relevant information about what is going on with the service. I had a hunch that maybe there was some outdated dependency that was causing the issue, and it had been about two months since I had updated my `packages.json` so I did an `npm outdated` and `npm upgrade`, pushed a new version of the app and haven't seen the issue since. My plan is to move the app over to Azure containers for better observability,  but the issue was definitely with some obscure dependency causing the app the crash. It sucks that Azure doesn't let you restart those apps or that they don't monitor those apps (I believe they run in IIS) and just restart them when they blow up.

**Comment by LongOddCode** [comment]
The failures occurred when the underlying application instance was starting up (“cold start”) and did not become ready before the upstream request timeout.

The application’s startup (cold start) time was longer than the maximum time allowed for a single request to wait for a response (45 seconds). When startup exceeded that limit, the request timed out and a `500` was returned.

We are taking steps to reduce or avoid cold-start related timeouts:

- Reduce application startup time so it consistently becomes ready within the request timeout.
- Keep the application warm (where supported) to prevent cold starts after idle periods.
- Add/validate lightweight warm-up and health checks to ensure traffic is served only after the app is ready.

**Comment by Tottzi** [comment]
> The failures occurred when the underlying application instance was starting up (“cold start”) and did not become ready before the upstream request timeout.
> 
> The application’s startup (cold start) time was longer than the maximum time allowed for a single request to wait for a response (45 seconds). When startup exceeded that limit, the request timed out and a `500` was returned.
> 
> We are taking steps to reduce or avoid cold-start related timeouts:
> 
> * Reduce application startup time so it consistently becomes ready within the request timeout.
> * Keep the application warm (where supported) to prevent cold starts after idle periods.
> * Add/validate lightweight warm-up and health checks to ensure traffic is served only after the app is ready.

Nice, we’ve got the reason now then. Thanks!

**Comment by daglas4ever** [comment]
I have had this issue for a while, I have upgraded next & react from
"next": "15.3.2",
"react": "^19.0.0", 
to 
"next": "^16.1.6",
"react": "^19.2.4"

and I am not getting the error again (been a month now, used to get it on daily basis)

**Comment by Geertvdc** [comment]
> The failures occurred when the underlying application instance was starting up (“cold start”) and did not become ready before the upstream request timeout.
> 
> The application’s startup (cold start) time was longer than the maximum time allowed for a single request to wait for a response (45 seconds). When startup exceeded that limit, the request timed out and a `500` was returned.
> 
> We are taking steps to reduce or avoid cold-start related timeouts:
> 
> * Reduce application startup time so it consistently becomes ready within the request timeout.
> * Keep the application warm (where supported) to prevent cold starts after idle periods.
> * Add/validate lightweight warm-up and health checks to ensure traffic is served only after the app is ready.

Any updates on this? my website which is not used often still has these issues when trying to use in cold start scenarios.

also am on newest pacakges like post above here mentions being the fix. it's not the fix. it's the Azure infrastructure that is the problem

**Comment by Yelinz** [comment]
Probably related problems https://github.com/Azure/static-web-apps/issues/801#issuecomment-4707422297

As I havent seen this link in the issue https://learn.microsoft.com/en-us/azure/static-web-apps/apis-overview#constraints

> API constraints
> 
> The following constraints apply to all API backends:
> 
>   Each static web app environment can only be configured with one type of backend API at a time.
>     The API route prefix must be /api.
>     Route rules for APIs only support [redirects](https://learn.microsoft.com/en-us/azure/static-web-apps/configuration#define-routes) and [securing routes with roles](https://learn.microsoft.com/en-us/azure/static-web-apps/configuration#securing-routes-with-roles).
>     Only HTTP requests are supported for APIs. WebSocket, for example, is not supported.
>     **The maximum duration of each API request 45 seconds.**
>     Network isolated backends are not supported.

One "simple" switch is to go to a "Web App" resource instead of SWA, thats what we did for our next.js project

**Comment by richardhomewood** [comment]
We discovered, with Azure, that the Backend (managed) service that came default is actually a free tier, and has low resources, specifically for I/O. The recommendation we received was to deploy a custom backend through App Service, at which point we decided to just use App Service.
