### ISSUE TITLE
Build pipeline ignore defined node version in package.json and azure-pipelines.yml.

### ISSUE THREAD

**Issue by welsea** [Azure/static-web-apps#1567]
**Describe the bug**

Build pipeline ignore defined node version defined in `package.json` and `azure-pipelines.yml`.

In`package.json` I have:
```json
{
   //...
  "engines": {
    "node": ">=20.15.0",
    "npm": ">=10.7.0"
  },
  "dependencies": {
    "next": "14.2.6",
    "next-auth": "^4.24.8",
    "react": "^18",
    "react-dom": "^18",
  },
  "devDependencies": {
    "@svgr/webpack": "^8.1.0",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.2.6",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
}

```

and in `pipelines.yml` i have:
```yml
  - task: NodeTool@0
    inputs:
      versionSpec: '20.15.0'
    displayName: 'Use Node.js 20.15.0'

  - script: |
      echo "After setting Node.js version:"
      node -v
      npm -v
    displayName: 'Check Node.js version after setting'

  - script: |
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      source ~/.nvm/nvm.sh
      nvm install 20.15.0
      nvm use 20.15.0
      node -v
      npm -v
    displayName: 'Install and use Node.js 20.15.0 with nvm'

  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
      app_location: "/" 
      output_location: ".next" 
      api_location: ""
```
the node version shows 20.15.0 after first three steps, but when build  azure static web app, the log shows `detecting platforms, nodejs:22.9.0` then ignore the previous defined version and use 22.9.0. but auzre pipeline doesn't support node v22 then lead to failed pipeline run.
```log
Detecting platforms...
Detected following platforms:
  nodejs: 22.9.0
Version '22.9.0' of platform 'nodejs' is not installed. Generating script to install it...
Detected the following frameworks: Typescript,Next.js
```

```log
---End of Oryx build logs---
Try to validate location at: '/...swa-oryx/app/.next'.
Finished building app with Oryx
Node version 22.9.0 is not supported. Please use one of the following versions 12, 14, 16, 18, 20.
````

**Expected behavior**
Use defined node version.

**Additional context**
Same pipeline file runs successfully with defined node version at Oct. 17

**Comment by welsea** [comment]
fixed issue by use:
```json
  "engines": {
    "node": "20.15.0",
    "npm": "10.7.0"
  },
```

**Comment by joonaojapalo** [comment]
I think the underlying issue is still valid. Shouldn't Oryx be able to choose supported Node engine if available with respect to `engines.node`?
