### ISSUE TITLE
SWA AAD Auth: 500: Internal Server Error

### ISSUE THREAD

**Issue by deanlongstaff** [Azure/static-web-apps#1582]
Hello,

Since this morning all static web apps i host have become unusable and returning a 500 error message. This appears to be consistent will all apps using the EntraID built-in authentication:

![Image](https://github.com/user-attachments/assets/1755dd0a-5934-4dce-92b9-107dc2bd37a1)

The 500 error seems to be occuring at the .auth/ endpoint:

![Image](https://github.com/user-attachments/assets/7ee3df08-dc8c-484f-990d-bfde4df54ce4)

There have been no changes to these apps but they are all consistently showing the same symptoms.

Auth Config:
```
"auth": {
    "rolesSource": "/api/auth/getRoles",
    "identityProviders": {
      "azureActiveDirectory": {
        "userDetailsClaim": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name",
        "registration": {
          "openIdIssuer": "https://login.microsoftonline.com/<TenantId>",
          "clientIdSettingName": "<ClientIdSettingName>",
          "clientSecretSettingName": "<ClientSecretSettingName>"
        }
      }
    }
  },
```

**Comment by obosdalen** [comment]
We are seeing the same on multiple different apps since Friday. Other apps not using the built in Entra auth seems to be working as intended.

**Comment by Huppie** [comment]
We're seeing the same on multiple apps. Tried redeploying our bicep, our content, changing the auth flow between v1 and v2 to no avail.

**Comment by deanlongstaff** [comment]
Yep, looks like Microsoft has made a change somewhere which has broken the custom azureActiveDirectory authentication provider. 

Currently have a case open with them but it's proving difficult to get someone to acknowledge the problem.

**Comment by Huppie** [comment]
Jep, same here @deanlongstaff

I've also created an X account just to message `@AzureSupport` and to get their attention to this issue. I'm glad it's 'just' an internal tool that's broken (even though it's a critical tool for one of our teams), it's like pulling teeth 🤯

**Comment by Huppie** [comment]
Just wondering why we seem to be the only ones @deanlongstaff and @obosdalen ... do you store the appkey+appid for the app registration in keyvault or have you stored those directly in environment variables?

**Comment by deanlongstaff** [comment]
@Huppie The clientID is plain text but the secret if pulled from key vault. Have tried all combinations of getting this to work though, inclusing plain text, and it consistently does not work. Perhaps most users are using traditional auth methods like msal-node instead of the SWA easy auth offering.

From my ticket with Microsoft it seems they have acknowledged that this is an outage on their end and they are conducting a RCA.

**Comment by Huppie** [comment]
I'm glad they at least acknowledged the issue to you. https://status.azure.com still says everything's fine 🤷‍♂

**Comment by obosdalen** [comment]
Same here, opened a ticket yesterday and they acknowledged the issue. Was told they are currently investigating. Been over 24 hours now since last update (even though I requested an update several hours ago).

**Comment by warlof** [comment]
Facing the same issue actually with deployments made since yesterday.
We did a deployment on friday which was successfully completed though.

Friday Docker image from Oryx stack was this one :

```
Digest: sha256:9b045c2011c2e132c0c5285e7de47584d8bdc1d6b06d021f76f2f90ac667fef9
Status: Downloaded newer image for mcr.microsoft.com/appsvc/staticappsclient:stable
```

The one used since monday is that one :

```
Digest: sha256:41473a2ebc45daa6e63c82a7f32a5680b0fe34dac49ab85dd6369c764b191308
Status: Downloaded newer image for mcr.microsoft.com/appsvc/staticappsclient:stable
```

While using **Diagnose and solve problems** from the Azure Static Web App resource, this is what we can get :

![Image](https://github.com/user-attachments/assets/897a4cc7-f396-4a1a-bf6c-610f12cf1955)

![Image](https://github.com/user-attachments/assets/3fb7b602-90df-4d1c-98a9-e80d63c7aee0)

I got the feeling the `staticwebapp.config.json` file is non longer uploaded properly - but I'm unsure :(

**Comment by deanlongstaff** [comment]
@warlof I noticed that in the diagnosis section too and pointed it out to the MS engineer. Definitely something wrong with how the auth config is being parsed or loaded on the SWA backend.

**Comment by james-nash** [comment]
FWIW, we're experiencing the exact same issue.

When I check our app's "Diagnose and solve problems", I also see the same message @warlof gets: "Unable to fetch Static App Config. Please try again later"

**Comment by deanlongstaff** [comment]
Should be fixed now guys 🎉. Will keep this issue open for a couple days until happy.

**Comment by james-nash** [comment]
Thanks @deanlongstaff. I can confirm that our site is working again now.

**Comment by warlof** [comment]
> Should be fixed now guys 🎉. Will keep this issue open for a couple days until happy.

I've been able to load css files - but still getting a lot of HTTP 500 on my side :(

**Comment by deanlongstaff** [comment]
@warlof Me too, a little intermittent at the moment. I think they are still working on fixing it properly.

**Comment by Huppie** [comment]
Everything seems back to normal here too, only ~3.5 days of downtime, no biggie... 😬 

No official response from Microsoft on our side though. My last update (after @deanlongstaff already posted he got an update that it was fixed) says they're still waiting for an update 🙈 

--- 

Update: Microsoft confirmed the fix 🙂
