### ISSUE TITLE
Deployment Failure Reason: An unknown error has occurred.

### ISSUE THREAD

**Issue by miklen** [Azure/static-web-apps#348]
I've created SWA resource in Azure, and connected it to my GitHub repo, where it created the deployment workflows. I started out trying a deployment without an api-location, and that worked fine. I then moved my Azure Function code from it's separate repo into an `api/` folder and pointed the api-location to the path for the functions project and retried deployment. This time it fails with an unknown error while trying to deploy the Azure Function.

```
Function Runtime Information. OS: Windows, Functions Runtime: v3, .NET Core version: 3.1
Finished building function app with Oryx
Zipping App Artifacts
Done Zipping App Artifacts
Zipping Api Artifacts
Done Zipping Api Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.2428578(s)
Status: InProgress. Time: 15.4844796(s)
Status: InProgress. Time: 30.8256391(s)
Status: InProgress. Time: 45.9461007(s)
Status: InProgress. Time: 61.1216657(s)
Status: InProgress. Time: 76.2432086(s)
Status: Failed. Time: 91.581539(s)
Deployment Failed :(
Deployment Failure Reason: An unknown error has occurred.
```

**Comment by miklen** [comment]
So I just found out that you can't create consumption plan Azure Functions on the Free Trial subscription, and that's probably what's causing this to fail.

A more helpful error would be nice though.

**Comment by anthonychu** [comment]
That shouldn’t be the problem (we’ve also fixed the issue that was incorrectly blocking consumption functions on free/trial subscriptions, it’s currently rolling out).

We need to take a closer look at this. Do you mind leaving your repo where it is while we investigate?

**Comment by miklen** [comment]
@anthonychu I had already begun moving to deploying in to a regular Function App when I saw your message. I have created a branch with the problem for you, and it still fails with the same error:

https://github.com/miklen/ezdinner-vue/runs/2267902001?check_suite_focus=true
https://github.com/miklen/ezdinner-vue/tree/swa-api-deployment

**Comment by wdorsett84** [comment]
Hello @anthonychu , any word on this issue? My initial github action succeeded on main branch however after making modifications to the API and Client app, I began receiving this error above as part of a pull request to main as well as a push to main.

**Comment by anthonychu** [comment]
@wdorsett84 can you please share the repo you’re using if it’s public? Otherwise can you share some logs from the GitHub action run?

**Comment by wdorsett84** [comment]
[github_action_log.log](https://github.com/Azure/static-web-apps/files/6402826/github_action_log.log)

@anthonychu Attached is the log file. It's a private repo. I won't be able to share it here. I hope this helps.

**Comment by anthonychu** [comment]
Thanks that’s helpful. @miwebst can you please take a look?

**Comment by miwebst** [comment]
Hey @wdorsett84, to ensure we are looking at the right app, do you mind giving us the default hostname (yellow-sea-12121) or the resource group and resource name? We can probably make a guess based on the time of the failure but want to be sure.

**Comment by wdorsett84** [comment]
Sure @miwebst It's calm-bush-038a5c310.

**Comment by miwebst** [comment]
Thanks @wdorsett84 it seems like the function app is not able to start up. We have an update coming to make this failure message more descriptive. As for the function app issue, @annaji-msft can you see what's going on?

**Comment by wdorsett84** [comment]
@miwebst @annaji-msft Hi. Any word on this?

**Comment by annaji-msft** [comment]
SyncTriggers failed with error below
"System.InvalidOperationException : No authentication handler is registered for the scheme 'ArmToken'. The registered schemes are: Bearer. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("ArmToken",...)

Could be related to https://github.com/Azure/azure-functions-host/issues/6805

@anthonychu Anything that @wdorsett84 do to mitigate the issue?

**Comment by miklen** [comment]
@annaji-msft I'm using the Azure Function authentication from Microsoft.Identity.Web (https://github.com/AzureAD/microsoft-identity-web/pull/856). I also have the error mentioned here https://github.com/Azure/azure-functions-host/issues/7330.

Could that be what's making the deployment fail?

**Comment by vangelkolarov-actioncamvideo** [comment]
Hi guys, I'm facing the same **Deployment Failed** issue. I created a couple of similar projects but after a few commits, I started getting this error and I can not continue working on the projects. Here are the actions from the public repo: [https://github.com/vangelkolarov-actioncamvideo/clone-of-blazor-starter/actions](https://github.com/vangelkolarov-actioncamvideo/clone-of-blazor-starter/actions). My default hostname at Azure is **calm-field-0f865**.
