### ISSUE TITLE
Cookies with sameSite or domain properties are not sent to client (non-local env)

### ISSUE THREAD

**Issue by benank** [Azure/static-web-apps#760]
**Describe the bug**

When sending cookies as a response to a request in an included functions API (as part of a static web app), the cookies are not sent if they include the `sameSite` or `domain` properties. This only occurs in a deployed static web app - this issue is not present in local testing of the API functions.

**To Reproduce**
1. Create static web app with an API. Host it on Github and use a GH workflow to deploy to Azure static web apps.
2. Set a cookie on the response with the `sameSite: true` or `domain: "domain.com"`.
3. Deploy static web app. 
4. Visit static web app API page (eg. /api/test) and inspect cookies in browser.
5. Observe that the cookie was not set.

GitHub Actions workflow YAML file and staticwebapp.config.json files: [files.zip](https://github.com/Azure/static-web-apps/files/8267813/files.zip)

**Expected behavior**
The cookie should be set, just like how it works when testing API functions locally with `func start`.

**Device info (if applicable):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 98.0.1

**Comment by rprasath** [comment]
Is there any update on this issue. I am facing the same issue. Azure static web app reverse proxying the app service removes the cookie from response

**Comment by kayakingcoder** [comment]
I'm trying to write something to my browser's localstorage. Works locally, but doesn't work when deployed on static webapp.
As localstorage and cookies are "the same thing" in many cases, I wonder if I'm experiencing the same problem.

**Comment by MagicMaxxx** [comment]
Hi, any update on this issue? Having the same issue described above...

**Comment by marcingolenia** [comment]
+1

**Comment by mushrune** [comment]
If we could get an update on this, that would be excellent. Not being able to pass any cookies to the browser locks you into the auth mechanisms Azure SWAs offer, which is frustrating if you are using an auth provider that is not supported by azure SWAs.

**Comment by zebleck** [comment]
also getting the error. no cookies being set when deployed

**Comment by OwaisAD** [comment]
Same issue. Static Web App as the client and Web App as the server. Locally it works sending a cookie and removing it on sign out, but deployed it doesn't set the cookie.....

**Comment by paliandris02** [comment]
> Same issue. Static Web App as the client and Web App as the server. Locally it works sending a cookie and removing it on sign out, but deployed it doesn't set the cookie.....

Hello, I am facing this issue right now, have you found any workaround to this?

**Comment by OwaisAD** [comment]
> > Same issue. Static Web App as the client and Web App as the server. Locally it works sending a cookie and removing it on sign out, but deployed it doesn't set the cookie.....
> 
> Hello, I am facing this issue right now, have you found any workaround to this?

Hello,
Yea I managed to fix it by creating a cookie that has `httpOnly: true`, `secure: true`, `secureOnly: true`, `sameSite: "None"`.  Also for my CORS configuration my allowedHeaders are `["Content-Type", "Access-Control-Allow-Headers", "Access-Control-Allow-Credentials"]` with `credentials: true`. Are you getting any errors?

**Comment by sethdorris** [comment]
> > > Same issue. Static Web App as the client and Web App as the server. Locally it works sending a cookie and removing it on sign out, but deployed it doesn't set the cookie.....
> > 
> > 
> > Hello, I am facing this issue right now, have you found any workaround to this?
> 
> Hello, Yea I managed to fix it by creating a cookie that has `httpOnly: true`, `secure: true`, `secureOnly: true`, `sameSite: "None"`.  Also for my CORS configuration my allowedHeaders are `["Content-Type", "Access-Control-Allow-Headers", "Access-Control-Allow-Credentials"]` with `credentials: true`. Are you getting any errors?

Are you using identity on your back end? Or did you manually create your cookie on the backend to get this to work?
My react app is a static web app and I can't get it to send my cookie to my API

**Comment by paliandris02** [comment]
> > > Same issue. Static Web App as the client and Web App as the server. Locally it works sending a cookie and removing it on sign out, but deployed it doesn't set the cookie.....
> > 
> > 
> > Hello, I am facing this issue right now, have you found any workaround to this?
> 
> Hello, Yea I managed to fix it by creating a cookie that has `httpOnly: true`, `secure: true`, `secureOnly: true`, `sameSite: "None"`.  Also for my CORS configuration my allowedHeaders are `["Content-Type", "Access-Control-Allow-Headers", "Access-Control-Allow-Credentials"]` with `credentials: true`. Are you getting any errors?

My problem was that my Static web app blocked the cookie, because the root domain of the app service was not the same as the static web app obviously. Therefore a I bought a domain and in Azure I added it as a custom domain. And I set the cookie domain param to the domain I bought and now it works.

**Comment by OwaisAD** [comment]
> > > > Same issue. Static Web App as the client and Web App as the server. Locally it works sending a cookie and removing it on sign out, but deployed it doesn't set the cookie.....
> > > 
> > > 
> > > Hello, I am facing this issue right now, have you found any workaround to this?
> > 
> > 
> > Hello, Yea I managed to fix it by creating a cookie that has `httpOnly: true`, `secure: true`, `secureOnly: true`, `sameSite: "None"`.  Also for my CORS configuration my allowedHeaders are `["Content-Type", "Access-Control-Allow-Headers", "Access-Control-Allow-Credentials"]` with `credentials: true`. Are you getting any errors?
> 
> Are you using identity on your back end? Or did you manually create your cookie on the backend to get this to work? My react app is a static web app and I can't get it to send my cookie to my API

I create cookies manually in my backend. It might be CORS configurations in your case. Remember to use `credentials: "include"` or `credentials: true`.

**Comment by idan** [comment]
We're running into this as well. There's no visibility or documentation about how cookies get stripped out from responses and how to control this behavior.

**Comment by idan** [comment]
I've created a minimal testcase showing this off:

https://github.com/githubnext/azureswacookies

**Comment by IvanJobs** [comment]
@idan  thanks for making this repro repo. I'm looking into this issue right now and will come back once I got more insights.

**Comment by IvanJobs** [comment]
I didn't reproduce it by my own repo https://github.com/IvanJobs/vanilla-api. Is there anything else I should align so that I can repro it?

**Comment by idan** [comment]
@IvanJobs hmm, I don't know.

Were you able to repro with the sample repo I provided?

It happens 100% consistently there.

**Comment by idan** [comment]
The mystery was resolved: Azure silently discards cookies with very long `max-age`. In this case, the cookie's `max-age` was set to 1000 years so as to effectively have no max-age. Azure silently removed the cookie.

My issue might not be related to _this_ issue, so leaving this here for future folks running into trouble.

Thanks @IvanJobs for help with the investigation!

**Comment by matissePe** [comment]
We still can't clear a cookie this way:

`Set-Cookie: Auth=; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Path=/; Secure; SameSite=Lax; HttpOnly`

This is quite annoying.
Any updates?

**Comment by Marl-Bermudo-TX** [comment]
I'm having the same issue. 

Previous setup. I have a blazor web assembly as the main app deployed in a SWA with custom domain `main.example.com`, and then there are 2 Vue apps in SWA, lets name them vue1 and vue2, with custom domain `vue1.example.com` and `vue2.example.com`, and an azure function nodejs with custom domain `api.example.com` and a custom jwt authentication. 

The new requirement force us to use only the `main.example.com` and put the others as a path. So new setup is now main app for the fallback route, `/vue1` and `/vue2` path for the respective vue apps, and `/api` for azure function by utilizing SWA BYOF on domain `main.example.com`. After the linking, the cookies are not sent to `main.example.com`, whereas previous setup we don't have problem. This is breaking changes since the vue apps rely on the cookies for some fetching values.

Additionally, since there are still some user of `api.example.com`, they now experiencing 401 even if the token is valid, so after going to Azure Function Portal > Settings > Authentication > unlink SWA, users of `api.example.com` can now access it again, so this fix only this problem. And after that, trying to connect to both `api.example.com` and `main.example.com/api` via postman, the cookies are received, so it has high probability that SWA is the one stripping the cookies.

Cookie settings
```
{
  httpOnly: true,
  secure: true,
  path: "/", // tried also the path "/api"
  sameSite: "None", // tried "Lax"
  maxAge: ONE_HOUR_AGE,
  domain: ".example.com" // tried also to use parsed host of headers["x-ms-original-url"]
}
```

Any variation of the above cookie, none is being received on the frontend

**Comment by MxNbrt** [comment]
I got it to work by changing 
``` js
import { serialize } from 'cookie';

return serialize('mySessionToken', "", {
  httpOnly: true,
  secure: true,
  sameSite: "strict",
  path: '/',
  expires: new Date(0),
});
```
to 
``` js
import { serialize } from 'cookie';

return serialize('mySessionToken', "", {
  httpOnly: true,
  secure: true,
  sameSite: "strict",
  path: '/',
  maxAge: 0,
});
```

I guess that Microsoft does not allow the `expires: new Date(0)` variant for deleting cookies but just the "new" variant `maxAge: 0` as stated in [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Set-Cookie#max-agenumber)

Note that this is also proposed in the [Microsoft learn Q&A](https://learn.microsoft.com/en-us/answers/questions/1321274/(static-webapp-with-managed-function)-set-cookie-w#answer-1282227)
