### ISSUE TITLE
ARM Validation issue - The repository url must be a DevOps repository

### ISSUE THREAD

**Issue by spawnrider** [Azure/static-web-apps#767]
**Describe the bug**

I am trying to deploy my Static Web App ressource using an ARM template.

**To Reproduce**
1. Create the following ARM template
2. Validate it

Here is a part of the ARM template :
```
        {
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2021-04-01",
            "name": "nestedTemplateSWACms",
            "properties": {
                "mode": "Incremental",
                "template": {
                    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
                    "contentVersion": "1.0.0.0",
                    "resources": [
                        {
                            "type": "Microsoft.Web/staticSites",
                            "apiVersion": "2021-03-01",
                            "name": "[parameters('SWAName')]",
                            "location": "[parameters('SWALocation')]",
                            "tags": "[parameters('ResourceTags')]",
                            "sku": "[parameters('SWASku')]",
                            "properties": {
                                "repositoryUrl": "[parameters('SWARepoUrl')]",
                                "branch": "[parameters('SWARepoBranch')]",
                                "stagingEnvironmentPolicy": "Enabled",
                                "allowConfigFileUpdates": true,
                                "provider": "DevOps",
                                "enterpriseGradeCdnStatus": "Disabled"
                            }
                        }
                    ]
                }
            }
        },
```
Note that the SWARepoURL variable is :
`https://<mycontext>.visualstudio.com/<project>/_git/swa-widget`

Then, the error message : 
```
ValidationForResourceFailed - Validation failed for a resource. Check 'Error.Details[0]' for more information.
ValidationForResourceFailed - The repository url must be a DevOps repository.
```

**Expected behavior**
The Static web app deployment

**Screenshots**

**Additional context**

**Comment by spawnrider** [comment]
Well, disabling the repository by setting the Provider to 'None' seems to be a workaround to deploy the service.

Is there a new control on the repository URL and especially on the domain ? 
https://dev.azure.com/{organization} (NEW version) versus https://{organization}.visualstudio.com (OLD one)

**Comment by NoremacNergfol** [comment]
Ran into the same issue.

Using https://{organization}.visualstudio.com fails template validation. Using https://dev.azure.com/{organization} asks for a repository token.

Subsequent incremental deployments fail when setting provider to 'none' or properties to an empty object. "Provider is invalid.  Cannot change the Provider. Please detach your static site first if you wish to use to another deployment provider."

Incremental deployments are off the table until the template validation issue is resolved. The AzureStaticWebApp build pipeline task sets the url to https://{organization}.visualstudio.com

**Comment by nicksimmonds-lmk** [comment]
I've also started getting this error.  Because our code is in GitHub and deployed using Azure DevOps the 'provider' is set as 'Devops' but the 'repositoryUrl' is a GitHub url.
Apart from it being annoying having to define these in the bicep template, even though we are just uploading the code and not having the Static Web App 'build' it, this used to work until a few days ago.

**Comment by miwebst** [comment]
It looks like our most recent ARM release has added some invalid validation that is causing this issue. We will work on 
1. fixing the DevOps repo validation
2. relaxing these requirements overall, a lot of these were in place before deployments from DevOps were allowed and not valid for most scenarios

**Comment by jslowack** [comment]
Just to give some additional input on this issue. Below is an example of a minimal ARM template configuration that is not working anymore.

```


{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "name": {
            "type": "string"
        },
        "sku": {
            "type": "string",
            "defaultValue": "Free"
        },
        "skucode": {
            "type": "string",
            "defaultValue": "Free"
        }
    },
    "resources": [
        {
            "type": "Microsoft.Web/staticSites",
            "apiVersion": "2021-01-15",
            "name": "[parameters('name')]",
            "location": "westeurope",
            "sku": {
                "name": "[parameters('sku')]",
                "tier": "[parameters('skuCode')]"
            },
            "properties": {
                "repositoryUrl": "https://dev.azure.com/xxx/xxx/_git/xxx",
                "branch": "master",
                "provider": "DevOps"
            }
        }
    ]
}
```

**Comment by marlier** [comment]
Setting the provider to 'None' is not a workaround for all use cases.

My use case: 
- I have an azure pipeline that does PR builds. 
- When a branch is updated, it provisions the infrastructure defined in a bicep template file -- creating if it does not exist, or updating if it does.
- The code in that branch is deployed to the PR infrastructure
- On further pushes to the branch (in response to comments, etc) the code is re-deployed.

With provider == 'None', the initial push works as expected.  Further pushes result in the error: 
```
##[error]BadRequest: Provider is invalid.  Cannot change the Provider. Please detach your static site first if you wish to use to another deployment provider.
```

Unfortuanately it's not possible to set the provider to 'DevOps' and point to our repo URL as repositoryUrl, because only 'https://dev.azure.com/...' repo locations pass validation for the repository URL, and we have an org URL instead.

I've worked around this by adding an AzureCLI task that checks for the existence of the expected infrastructure, sets a variable, and then a condition on the Resource Manager Template deploy that skips it if everything exists.  That's obviously not ideal, though.

**Comment by mrdobing** [comment]
Any updates on this?

**Comment by miwebst** [comment]
This should be fixed now! Again sorry for the inconvenience.

**Comment by nicksimmonds-lmk** [comment]
This is still not working for me. I have removed provider, repositoryUrl and branch from our bicep template but when I deploy the template to a static web app that has code deployed to it I still get the error:
RepositoryUrl is invalid. The repository url does not match the format of a DevOps repository.

**Comment by miwebst** [comment]
Can you change the provider to 'Custom'? We will be adding clearer docs on how we recommend to work with ARM/BICEP in the future.

**Comment by nicksimmonds-lmk** [comment]
@miwebst Chaning provider to 'Custom' has worked.  Thank you.
