### ISSUE TITLE
Upload Timed Out. Unsure if deployment was successful or not.

### ISSUE THREAD

**Issue by ansmah** [Azure/static-web-apps#942]

**Comment by ansmah** [comment]
##[error]Error: The process '/usr/bin/bash' failed with exit code 1

When executing from Azure DevOps will get this message sporadically.  On subsequent retries we will have some success.

**Comment by mkarmark** [comment]
Can you please provide the app details so we can investigate? If you don't feel comfortable sharing them here, feel free to file a support ticket.

**Comment by ansmah** [comment]
> Can you please provide the app details so we can investigate? If you don't feel comfortable sharing them here, feel free to file a support ticket.

Currently only static content, we have the following files.  app.js, config.json, favicon.ico, index.html, readme.md and vancity.css

**Comment by ssyrell** [comment]
@mkarmark I am also running into this issue. I have an app that is mostly unchanged from the react template. Deploying the app by itself works fine, but as soon as I add an API (I've tried both C# and typescript function apis), I get the timeout issue. It does seem to actually finish deploying, but it takes another 5 or so minutes for the API to show up in the "apis" section of my static web app in the azure portal.

My app can be found here if it helps: https://github.com/ssyrell/purpleair-dashboard

Here is a failed deployment: https://github.com/ssyrell/purpleair-dashboard/actions/runs/3221345766

**Comment by kaihei777** [comment]
me too...

**Comment by adam-javelin** [comment]
Having the same issue. Here is my error log: https://pipelines.actions.githubusercontent.com/serviceHosts/583c118f-1d9a-4ddc-862e-67a8e673d75e/_apis/pipelines/1/runs/1258/signedlogcontent/2?urlExpires=2022-10-14T02%3A18%3A10.5877322Z&urlSigningMethod=HMACV1&urlSignature=r038Sm4waknUQMjEtil0wTBx4PKBWIYL0zNCGX16cV4%3D

**Comment by andrewgbell** [comment]
Same issue here as well, details below, but essentially the upload occasionally times out.  Once it does, as mentioned in other reports, it will generally fail a few times and then start succeeding a few times.  We have less success in the morning (GMT).

DeploymentId: a85c6509-ff2e-4683-81ca-fa3ee09a11e0

App Directory Location: '/build' was found.
Looking for event info
Skipping step to build /github/workspace/build with Oryx
No Api directory specified. Azure Functions will not be created.
Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
Zipping App Artifacts
Done Zipping App Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 2.9537861(s)
Status: InProgress. Time: 18.054918(s)
Status: InProgress. Time: 33.1716091(s)
Status: InProgress. Time: 48.2877535(s)
Status: InProgress. Time: 63.4116473(s)
Status: InProgress. Time: 78.5275566(s)
Status: InProgress. Time: 93.6360356(s)
Status: InProgress. Time: 108.7403657(s)
Status: InProgress. Time: 123.8702754(s)
Status: InProgress. Time: 154.4016648(s)
Status: InProgress. Time: 184.6059351(s)
Status: InProgress. Time: 199.9511437(s)
Upload Timed Out. Unsure if deployment was successful or not.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting

**Comment by HaikoF** [comment]
We have the same problem, using a azure devops pipeline ( task AzureStaticWebApp@0).

**Comment by dligthart** [comment]
We also have this problem with azure static web app

**Comment by DavidTheSimon** [comment]
We also have this problem.

**Comment by FlashITSD** [comment]
Same issue... any workaround?

**Comment by jmsfilipe** [comment]
Same happening here... Any updates?

**Comment by mannyyang** [comment]
same issue as well

**Comment by lohithgn** [comment]
Facing the same issue today ... i created a full stack C# with Blazor & Az Fx all .NET7 ... GH action fails with the error - "Upload timed out. unsure if deoloyment was successful or not" ... and i have a demo in 1 hour time :(

**Comment by cmclellen** [comment]
Same

**Comment by CalvinQuark** [comment]
I encountered this issue while attempting to follow the [Build an Azure Static Web Apps website with Blazor and serverless API](https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-blazor?WT.mc_id=blazorstaticwebapps-social-aapowell) tutorial. I tried stepping through this tutorial three times. Each time the _Build and Deploy_ job failed reporting `Upload Timed Out. Unsure if deployment was successful or not.`

**Comment by bhavya444** [comment]
same issue

**Comment by MaxWilson** [comment]
This issue is back again.

**Comment by thangcx-1985** [comment]
same issue

**Comment by ahkian** [comment]
Same issue for me. 
`---End of Oryx build logs---
Function Runtime Information. OS: linux, Functions Runtime: ~4, node version: 16
Finished building function app with Oryx
Zipping Api Artifacts
Done Zipping Api Artifacts
Zipping App Artifacts
Done Zipping App Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.081344(s)
Status: InProgress. Time: 15.160747(s)
Status: InProgress. Time: 30.2418266(s)
Status: InProgress. Time: 45.537767(s)
Status: InProgress. Time: 60.7017447(s)
Status: InProgress. Time: 75.887511(s)
Status: InProgress. Time: 91.1048633(s)
Status: InProgress. Time: 106.2816092(s)
Status: InProgress. Time: 123.9764901(s)
Status: InProgress. Time: 139.1250957(s)
Status: InProgress. Time: 154.202578(s)
Status: InProgress. Time: 169.2889017(s)
Status: InProgress. Time: 185.0700385(s)
Status: InProgress. Time: [200](https://github.com/adversis-labs/adversis-ux/actions/runs/4178124810/jobs/7236546638#step:8:201).2424887(s)
Status: InProgress. Time: [215](https://github.com/adversis-labs/adversis-ux/actions/runs/4178124810/jobs/7236546638#step:8:216).3178695(s)
Status: InProgress. Time: 230.405882(s)
Upload Timed Out. Unsure if deployment was successful or not.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting`

**Comment by abdulpapalek** [comment]
HI is this resolve?, we keep running the same issue for a couple of times now

App Directory Location: 'out' was found.
Looking for event info
Skipping step to build /working_dir/out with Oryx
Using 'staticwebapp.config.json' file for configuration information, 'routes.json' will be ignored.
Api Directory Location: 'api' was found.
Skipping step to build /working_dir/api with Oryx
Function Runtime Information. OS: linux, Functions Runtime: ~4, node version: 16
Zipping Api Artifacts
Done Zipping Api Artifacts
Zipping App Artifacts
Done Zipping App Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.263987(s)
Status: InProgress. Time: 15.5313462(s)
Status: InProgress. Time: 30.8131698(s)
Status: InProgress. Time: 46.0440322(s)
Status: InProgress. Time: 61.2769718(s)
Status: InProgress. Time: 76.4715084(s)
Status: InProgress. Time: 91.6647405(s)
Status: InProgress. Time: 106.8436189(s)
Status: InProgress. Time: 122.1195995(s)
Status: InProgress. Time: 137.3141649(s)
Status: InProgress. Time: 153.2731447(s)
Status: InProgress. Time: 168.4570744(s)
Status: InProgress. Time: 183.6682158(s)
Status: InProgress. Time: 198.8815765(s)
Status: InProgress. Time: 214.1923525(s)
Status: InProgress. Time: 229.4028036(s)
Upload Timed Out. Unsure if deployment was successful or not.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
##[error]Error: The process '/usr/bin/bash' failed with exit code 1
Finishing: Deploy iot-web-prod

**Comment by otykier** [comment]
Same issue here. The "Environments" blade in the Azure portal seems to be stuck in the "Uploading" status:

![image](https://user-images.githubusercontent.com/8976200/225575992-2bfc679e-d2f1-4207-ba86-0868752e87eb.png)

**Comment by eduardotang** [comment]
same issue, 
and i only find out it did actually deploy successfully when i looked into the "Environments" blade in the portal, the status said "Ready"

**Comment by cjbadger** [comment]
+1

**Comment by phranger** [comment]
+1 

Just ran through the quick start and how-to guides in the [documentation](https://learn.microsoft.com/en-us/azure/static-web-apps/) and received this error.

**Comment by abdulpapalek** [comment]
Got a response from MS from our service request and apparently they found out that the timeout period for the deployment steps is hard coded and if file size is large in combination with some intermittent network issue then you'll encounter this error. The work around that MS suggested to us was either we breakdown our deployments into smaller chunks in the pipeline or deploy in a different time of the day(*When its not very busy which is before lunch time in our timezone) so as a high performing engineer I choose the latter(LOL) .. Its quite annoying cuz this means there is no guarantee that our hotfixes could be deployed in time since there is no guarantee that pipeline wont fail especially in the afternoon

**Comment by zjhch123** [comment]
@abdulpapalek do they offer any ETA for the fixing? I can't imagine they hard-code such a critical variable... 🤬

**Comment by abdulpapalek** [comment]
@zjhch123 not really, i dont think they are fixing it anytime soon which is a bummer because we'll be adding 2 new big packages

**Comment by AntoineSmet** [comment]
+1

**Comment by AntoineSmet** [comment]
Ok I find a solution just add

**- app_build_timeout_seconds: 1800**

on your file yml

**Comment by abdulpapalek** [comment]
@AntoineSmet  that is only for the build. Unfortunately there is no easy way around the deployment polling timeout. This is the sample code that MS sent us 



![Screen Shot 2023-05-24 at 11 17 20 AM](https://github.com/Azure/static-web-apps/assets/21253121/b041f2e0-39f2-4548-8b22-630f02c3b38e)

**Comment by waferbaby** [comment]
Hi friends! I'm running into this too - I've actually got two deployments going via one repo to different static web sites, and one always works, and the second seems to just time out (even when only one is running).

Example of the failure: https://github.com/waferbaby/usesthis/actions/runs/5888482073/job/15970408255

**Comment by kianryan** [comment]
We've just had the same problem on a critical site.  Deployment before 0900 before business hours, showing as "Uploading", but never resolving.  Multiple deployments not resolving.  This is /not/ a large deployment, but "wait until quiet" is not an acceptable solution.

**Comment by DavidVollmers** [comment]
Same issue for me since yesterday...

**Comment by roldengarm** [comment]
Yes, I also have the same issue, very frustrating. It was working fine when set up initially in March, but recently have seen this error occur randomly.

Is there any workaround or solution?

**Comment by DavidVollmers** [comment]
@roldengarm So for me at least it is working again. It seems to be a temporary, yet reoccuring problem...

**Comment by celsocoutinho-tangany** [comment]
I also had this issue a few days back for the first time, during my holidays, and redeploying now worked! A bit frustrating, especially considering the workaround given by MS

**Comment by roldengarm** [comment]
> @roldengarm So for me at least it is working again. It seems to be a temporary, yet reoccuring problem...

Yes, it is always working the second time, but it is very annoying as I have to re-run our pipeline manually.

**Comment by rosemcc** [comment]
Same issue here. Is there any update on this?

**Comment by hgbao** [comment]
Having the same issue here. And the environment has been stuck at `Updating` for days now. But the new code has already been uploaded successfully
![image](https://github.com/Azure/static-web-apps/assets/15858532/4d22b2ee-4485-4b8f-a885-80c2901fa7ac)

**Comment by GiladGershon** [comment]
same issue

**Comment by tejaswankalluri** [comment]
Same issue

**Comment by bluewilliams** [comment]
Same issue here, seemed to be timed with a major outage on the GitHub runner workload which has subsequently been resolved a couple hours back.

cite: https://www.githubstatus.com/history

**Comment by 58836980** [comment]
Same issue from today, it happens only in Production. Staging deployments are OK.

**Comment by tejaswankalluri** [comment]
> Same issue here. Start time of the event appears to be timed with a significant outage of the GitHub Actions/Runner workload which has subsequently been resolved a couple hours back.
> 
> cite: https://www.githubstatus.com/history

Yes but runners are working fine now. but still showing the same error

**Comment by tejaswankalluri** [comment]
created a new issue #1396

**Comment by javiercoh** [comment]
same here

**Comment by rezwanul-islam** [comment]
Re-run the same job in a different time. It might help.

**Comment by elad320011** [comment]
I get this error in Azure Devops after 600 seconds. Is there a resolution already?

**Comment by Cypher1** [comment]
I'm seeing this with the Github Actions Deploy in a staging build for a PR.

**Comment by thomasgauvin** [comment]
@elad320011 @Cypher1 are you deploying Next.js workloads? If so, can you share the region of your static web apps and its default hostname/url in the thread https://github.com/Azure/static-web-apps/issues/1427?

**Comment by casaltenburg** [comment]
Is there a fix already?

**Comment by IsaacHayes1995** [comment]
We are encountering this issue, any update on a fix?

**Comment by PushanAgrawal** [comment]
facing the same issue while deploying next application . any fix that pre exists? anything that can be changed in te workflow to bypass the error .

**Comment by NikulChd** [comment]
the same issue. is there any fix?? 
![image](https://github.com/user-attachments/assets/9491069a-6f06-487f-9f2f-32c347ae6648)

**Comment by trynyro** [comment]
facing same issue

**Comment by bloor** [comment]
![image](https://github.com/user-attachments/assets/2554f060-27f6-4460-935f-ecb02512d915)

**Comment by mike-rambil** [comment]
same issue here

**Comment by javiercoh** [comment]
same issue here

**Comment by mike-rambil** [comment]
> same issue here

I think it goes away if you try it a couple times

**Comment by tebeco** [comment]
> @AntoineSmet that is only for the build. Unfortunately there is no easy way around the deployment polling timeout. This is the sample code that MS sent us
> 
> ![Screen Shot 2023-05-24 at 11 17 20 AM](https://private-user-images.githubusercontent.com/21253121/240439702-b041f2e0-39f2-4548-8b22-630f02c3b38e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTk4NTAsIm5iZiI6MTcyNTQ1OTU1MCwicGF0aCI6Ii8yMTI1MzEyMS8yNDA0Mzk3MDItYjA0MWYyZTAtMzlmMi00NTQ4LThiMjItNjMwZjAyYzNiMzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDE0MTkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NjU3NTczZjI1YmU1MTY2YThiMmJiMGVkNDc4ZDBhZWFlZDNiZGRiZDZhNzUzYTRjYTdjNDlhYzI0NDI2YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SBK2zO8x4YRa3sGtX9DFXQDBeXTqwcxcryJjau249wE)

any idea where the code was from ?
because i'm suspecting issue for the NextJs Hybrid deploy being part of the CLI as well as some other stuff but I can't managed to debug it

**Comment by tebeco** [comment]
@abdulpapalek

**Comment by dluciano** [comment]
Found this issue today. Next 14.2, SSG, Global web app, GitHub is behind an organisation. Help please.

**Comment by dominikx96** [comment]
Same problem.

**Comment by Syed-Ahzam-Imam** [comment]
same problem

**Comment by marumori-tech** [comment]
Same Problem.

**Comment by alvdelci** [comment]
Same problem!

**Comment by sohocine** [comment]
Had same issue. Turns out, there's a 3000 files limit to the uploaded package. In my case, most of the files were located in `node_modules` and installed as dev dependencies.
Here's how I fixed it. The deployment is now successfully completing:
1. Added a custom build step in GitHub Actions workflow file with this:
```app_build_command: "npm run build:prod" # CustonBuild command for app```

2. Updated scripts section in my `package.json`
```
  "scripts": {
    "dev": "next dev",
    "install:clean": "rm -rf node_modules && npm install --omit=dev",
    "build": "next build",
    "build:prod": "npm install && npm run build && npm run install:clean",
    "start": "next start",
    "lint": "next lint",
    "check": "tsc --noEmit"
  },

```

**Comment by chandlerchao-ds** [comment]
This is still an issue. How has this not been solved yet?

Normally, I just try deploying multiple times and eventually it works after the 2nd or 3rd attempt. Today I'm not so lucky. 7 attempts and still nothing.

**Comment by Cypher1** [comment]
I am considering raising this as a deal breaker for using Azure's static web apps at my company's next founder's meeting.
Please resolve this in Q1

**Comment by tebeco** [comment]
funny enough this is not a timeout issue
after all few weeks of investigation it's a backplane failure to create the server part

also to note the tooling is apparently not designed at all to do "environment promotion" you have to rebuild everything everytime you go DEV > UAT > PRD

This means you'll never have reproducibility 

the SWA CLI was apparently never intended to ship built to upload pre-built package (even is it work but flacky)
source: azure ticket support

also anything touching NextJs in preview is in "abandoned state" and preview means that you should not even try it
source: azure ticket support

the cli in preview is xplat as it's not dealing with linux/mac/ windows path separator the same and will eventually delete your .git folder on windows but not linux with the exact same content for config
source: azure ticket support

the entire oryx build system was apparently only ever design for blazor but it's unclear if its finished or not


note: since Thomas Gauvin left for Cloudflare there's no community involvement from the team on this repo

it feels like this cannot be used for more than a glorified cdn / blob storage until some work is being redone seriously / cli fixed / people talking to the community / env promotion / backplane api creation fixed / proper SLA

**Comment by T89L** [comment]
I haven't been able to deploy in a week

**Comment by adam-javelin** [comment]
Login to you Azure Portal and go to Environments. You might have too many preview environments that need to be deleted first.   I had this or something similar.

**Comment by T89L** [comment]
> Login to you Azure Portal and go to Environments. You might have too many preview environments that need to be deleted first. I had this or something similar.

I appreciate the input. I deploy straight to prod for my personal business and don't do branches or PRs for this project so I've only ever had one environment. I have not seen this issue before until the past couple of weeks. Initially it would sometimes work retrying but it has since completely broken. I went through and cleaned a bunch of unused static assets and a few libs to slim down the deploy size and it's still broken. I guess I'll have to look into deploying by the CLI or using the standalone option because it appears support for this issue is never coming.

**Comment by lcf** [comment]
Trying to deploy a sample nextjs app with no changes, it fails with the same error

**Comment by T89L** [comment]
I had over 30 failed consecutive failed deployments over several days. I really needed to deploy so I ended up trying to standalone option and it worked and I do not see any downsides to the change. Interestingly while trying to disconnect and reconnect the github action in azure during troubleshooting I did at some point see an error that my file size exceeded the allowed limits which makes me wonder if the deployment fails right away but for some reason oryx doesn't get the message and just times out.

Also while looking for other solutions I found another large github issue where it was determined oryx is looking for .nextjs/health.html to verify a successful deployment. It seems like some people have some middleware that conflicts with that route so just another thing to check. 

Overall the support for this issue from MS is pretty disappointing this IS a paid product for some of us and it's crickets from the devs.

**Comment by chandlerchao-ds** [comment]
After far too many failures, I switched over to using an Azure App Service. I haven't had the problem since. I honestly think it has something to do with the 250Mb/500Mb max app size. When you package the code up with all the modules and build the container, I suspect it starts to exceed this size. Now, why it is inconsistent I haven't fully figured out. That is the argument against the theory.

Anyhow, you want pain relief...move to an App Service.

**Comment by casaltenburg** [comment]
Does someone has any update on this?

**Comment by hoangzuyss2412** [comment]
Still unresolved.

**Comment by mike-rambil** [comment]
> Does someone has any update on this?

it went away when I retried the deployment for me..not sure why

**Comment by carlohoanguyen** [comment]
> I had the same problem. I was able to resolve it after making some changes to the app's build settings.
> 
> In the package.json: I changed `"build": "next build"` for `"build": "next build && cp -r .next/static .next/standalone/.next/ && cp -r public .next/standalone/"`
> 
> And in the workflow file i added two new lines (31, 32) in the build settings:
> 
> ![Image](https://github.com/user-attachments/assets/b96d5652-afd5-4dee-a779-ef18131e6c4d)
> 
> I hope it also works for someone else [😊](https://emojipedia.org/smiling-face-with-smiling-eyes)

This worked for me.

Also try to configure the middleware for .swa health check

https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid#enable-standalone-feature
