### ISSUE TITLE
Internal Server Error 

### ISSUE THREAD

**Issue by Abdull-Rauf** [Azure/static-web-apps#963]
After successfull deployement of nextjs app on azure static web app, when I click on url it displays "Internal Server Error" instead of website content.

**Comment by vivekjilla** [comment]
Hi @Abdull-Rauf  
1. Are you using the `next export` feature of nextjs? If so, you might have to pass `is_static_export: true` in the workflow.yml. For more details on how to do this : https://learn.microsoft.com/en-us/azure/static-web-apps/nextjs#static-html-export
2. If you're trying the [nextjs ssr support](https://github.com/Azure/static-web-apps/discussions/921) we released recently, is it possible some app settings are missing for you app? You can add some logs and enable app insights to see where the errors are coming from. For more details: https://learn.microsoft.com/en-us/azure/static-web-apps/monitor

Please let us know if it helps.

**Comment by scott-gainous** [comment]
I have created a Next.js application that I have built and deployed with GitHub Actions workflow.  When I try to access the static web app via the host name provided, I get the same Internal Server Error.  The troubleshooting links didn't seem to solve my problem.  Digging into Application Insights, it is surfacing the following error:

Path doesn't exist!
Mono.Unix.UnixFileSystemInfo.AssertValid

Logs:
Category: Worker.HttpWorkerProcess.0dbffbc2-4fb7-44e3-bf14-20106b3f8c7d
Stack:
`System.InvalidOperationException:
   at Mono.Unix.UnixFileSystemInfo.AssertValid (Mono.Posix.NETStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)
   at Microsoft.Azure.WebJobs.Script.Workers.Http.HttpWorkerProcess.AssignUserExecutePermissionsIfNotExists (Microsoft.Azure.WebJobs.Script, Version=4.13.0.0, Culture=neutral, PublicKeyToken=null: /src/azure-functions-host/src/WebJobs.Script/Workers/Http/HttpWorkerProcess.cs:75)
`

**Comment by vivekjilla** [comment]
Not sure which particular library is causing this issue. You can add custom logs in your app using `console.log`, and get them to surface in the app insights. This might help with debugging this issue further.

**Comment by superhp** [comment]
I didn't manage to print any log with console.log. I also tried to implement NextJs custom loggers (https://nextjs.org/docs/advanced-features/custom-error-page#customizing-the-500-page) but they also don't work. It seems the app crashes even earlier on the app initialization.

**Comment by superhp** [comment]
@vivekjilla I found a simple NextJs sample app which also triggers same error message when deployed: https://github.com/restuwahyu13/nextjs-with-redux/. Do you see any reasons why?

**Comment by vivekjilla** [comment]
Thanks @superhp for the repro. I couldn't figure out what's wrong but I was able to make that app work by upgrading `next` and `next-redux-wrapper` to newer versions. 
Here's the diff in package.json: https://github.com/restuwahyu13/nextjs-with-redux/compare/main...vivekjilla:nextjs-with-redux:main#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
And the working site: https://calm-glacier-03663c610.2.azurestaticapps.net//

Hope this helps!

Just to give some more context wrt looking at the logs for Nextjs specifically.
- Generally, there should be a log with message `serving start: /` (if request is for `/` path) and another with message `serving end: / with status: <statuscode>`, and the logs between these two messages correspond to logs for that particular request.
- Generally, any other exceptions/logs outside these may not be relevant to your app logic.
- Look for the `message` column. other columns might not be that relevant in general.

**Comment by superhp** [comment]
Thank you, @vivekjilla! I finally understood what the issue was. Some of run-time required NPM packages were left in devDependencies block in packages.json. It was not an issue for SSG export case but the server side of SSR case was not too happy about these missing packages. When I moved them from devDependencies to dependencies, the app started working correctly.

**Comment by sulabh-msft** [comment]
@superhp Glad that you were able to resolve the issue. 

Please let us know if we can close the issue.

**Comment by superhp** [comment]
@sulabh-msft my issue was solved, but this ticket was opened by @Abdull-Rauf with a similar issue. @Abdull-Rauf do you still want to keep the issue open?

**Comment by Reshmi-Sriram** [comment]
Hi @Abdull-Rauf and @scott-gainous,
Hope you have the issues resolved as well. Closing this issue, feel free to re-open if it needs more investigation. Thanks!

**Comment by tekgiant** [comment]
@Reshmi-Sriram On the latest version of NextJS, this "Path does not exist" error is still an issue. Albeit intermittent, it's still an issue. I get this when using NextJS and NextAuth, after successfull signin, when the redirection to the callback endpoint for NextAuth happens, this error gets logged to App Insights and the managed API returns a 404. It never happens locally, and it's not an issue when deployed to Vercel, so it's pretty apparent that it's an Azure Static Web Apps issue.

**Comment by olavocarvalho** [comment]
Anyone solved this issue? I'm getting very similar error here. 
```
[{"severityLevel":"Warning","outerId":"0","message":"Path doesn't exist!","type":"System.InvalidOperationException","id":"38700158","parsedStack":[{"assembly":"Mono.Posix.NETStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51","method":"Mono.Unix.UnixFileSystemInfo.AssertValid","level":0,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Script, Version=4.21.0.0, Culture=neutral, PublicKeyToken=null","method":"Microsoft.Azure.WebJobs.Script.Workers.Http.HttpWorkerProcess.AssignUserExecutePermissionsIfNotExists","level":1,"line":75,"fileName":"/src/azure-functions-host/src/WebJobs.Script/Workers/Http/HttpWorkerProcess.cs"}]}]
```

**Comment by JarFrank** [comment]
I'm getting the same error `Path doesn't exist!`.
I'm using app directory and NextJs - 13.4.9
```
System.InvalidOperationException:
   at Mono.Unix.UnixFileSystemInfo.AssertValid (Mono.Posix.NETStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)
   at Microsoft.Azure.WebJobs.Script.Workers.Http.HttpWorkerProcess.AssignUserExecutePermissionsIfNotExists (Microsoft.Azure.WebJobs.Script, Version=4.21.0.0, Culture=neutral, PublicKeyToken=null: /src/azure-functions-host/src/WebJobs.Script/Workers/Http/HttpWorkerProcess.cs:75)
```

**Comment by dooman87** [comment]
Having the same issue after adding application insights. Simple PR with changes that causes the issue: https://github.com/OpenDDD/dddmelbourne-website-2024/pull/4/files
